---
language: perl
perl:
  - '5.12'
  - '5.14'
  - '5.18'
  - '5.20'
notifications:
  email: false
install:
  - dzil authordeps --missing | cpanm --notest
  - dzil listdeps |cpanm --notest
  - cpanm --notest -q --mirror-only --installdeps .
  - dzil install
script:
  - dzil test
